In [2]:
import tensorflow as tf

# Talk 1: Creating and Manipulating Matrices

# Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function
A = tf.random.normal(shape=(2, 2))

# Display the values of matrix A
print("Matrix A:")
print(A.numpy())

# Create a Gaussian matrix B with dimensions 2x2, using TensorFlow's truncated_normal function
B = tf.random.truncated_normal(shape=(2, 2))

# Display the values of matrix B
print("\nMatrix B:")
print(B.numpy())

# Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution
# with a mean of 2 and a standard deviation of 0.1
C = tf.random.normal(shape=(2, 2), mean=2, stddev=0.1)

# Display the values of matrix C
print("\nMatrix C:")
print(C.numpy())

# Perform matrix addition between matrix A and matrix B, and store the result in matrix D
D = tf.add(A, B)

# Display the result of matrix addition
print("\nMatrix D (Result of Addition A + B):")
print(D.numpy())

# Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E
E = tf.matmul(C, D)

# Display the result of matrix multiplication
print("\nMatrix E (Result of Multiplication C * D):")
print(E.numpy())

# Talk 2: Performing Additional Matrix Operations

# Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function
F = tf.random.uniform(shape=(2, 2))

# Display the values of matrix F
print("\nMatrix F:")
print(F.numpy())

# Calculate the transpose of matrix F and store the result in matrix G
G = tf.transpose(F)

# Display the transpose of matrix F (Matrix G)
print("\nMatrix G (Transpose of F):")
print(G.numpy())

# Calculate the element-wise exponential of matrix F and store the result in matrix H
H = tf.exp(F)

# Display the result of element-wise exponential
print("\nMatrix H (Element-wise Exponential of F):")
print(H.numpy())

# Create a matrix I by concatenating matrix F and matrix G horizontally
I = tf.concat([F, G], axis=1)

# Display the horizontally concatenated matrix I
print("\nMatrix I (Horizontally Concatenated F and G):")
print(I.numpy())

# Create a matrix J by concatenating matrix F and matrix H vertically
J = tf.concat([F, H], axis=0)

# Display the vertically concatenated matrix J
print("\nMatrix J (Vertically Concatenated F and H):")
print(J.numpy())


/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

Matrix A:
[[ 1.6362427  1.7600968]
 [-0.6661531  0.2341998]]

Matrix B:
[[0.25425696 0.69706833]
 [0.5611164  0.47779745]]

Matrix C:
[[1.9695902 2.0166566]
 [2.057621  1.8833722]]

Matrix D (Result of Addition A + B):
[[ 1.8904997   2.4571652 ]
 [-0.10503668  0.7119973 ]]

Matrix E (Result of Multiplication C * D):
[[3.5116868 6.2754626]
 [3.6921089 6.3968706]]

Matrix F:
[[0.39940596 0.37301576]
 [0.66564167 0.09256589]]

Matrix G (Transpose of F):
[[0.39940596 0.66564167]
 [0.37301576 0.09256589]]

Matrix H (Element-wise Exponential of F):
[[1.4909388 1.4521072]
 [1.9457387 1.0969855]]

Matrix I (Horizontally Concatenated F and G):
[[0.39940596 0.37301576 0.39940596 0.66564167]
 [0.66564167 0.09256589 0.37301576 0.09256589]]

Matrix J (Vertically Concatenated F and H):
[[0.39940596 0.37301576]
 [0.66564167 0.09256589]
 [1.4909388  1.4521072 ]
 [1.9457387  1.0969855 ]]
